export const ADD_ITEM = 'ADD_ITEM'
export const DECREASE_ITEM = 'DECREASE_ITEM'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const DELETE_ITEM = 'DELETE_ITEM'
export const SELECT_PRODUCT = 'SELECT_PRODUCT';